// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDq_iq6tkiebHmkCUiw3Ry70MdN3MesEs',
    appId: '1:861060933562:web:a62b88134707831d2df83b',
    messagingSenderId: '861060933562',
    projectId: 'smartdoor-fc63e',
    authDomain: 'smartdoor-fc63e.firebaseapp.com',
    databaseURL: 'https://smartdoor-fc63e-default-rtdb.firebaseio.com',
    storageBucket: 'smartdoor-fc63e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDq_iq6tkiebHmkCUiw3Ry70MdN3MesEs',
    appId: '1:861060933562:android:764ce8a54a0deb86a2df83',
    messagingSenderId: '861060933562',
    projectId: 'smartdoor-fc63e',
    databaseURL: 'https://smartdoor-fc63e-default-rtdb.firebaseio.com',
    storageBucket: 'smartdoor-fc63e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDq_iq6tkiebHmkCUiw3Ry70MdN3MesEs',
    appId: '1:861060933562:ios:b9b8b7b6b5b4b3b2b1b0',
    messagingSenderId: '861060933562',
    projectId: 'smartdoor-fc63e',
    databaseURL: 'https://smartdoor-fc63e-default-rtdb.firebaseio.com',
    storageBucket: 'smartdoor-fc63e.firebasestorage.app',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDq_iq6tkiebHmkCUiw3Ry70MdN3MesEs',
    appId: '1:861060933562:ios:b9b8b7b6b5b4b3b2b1b0',
    messagingSenderId: '861060933562',
    projectId: 'smartdoor-fc63e',
    databaseURL: 'https://smartdoor-fc63e-default-rtdb.firebaseio.com',
    storageBucket: 'smartdoor-fc63e.firebasestorage.app',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDq_iq6tkiebHmkCUiw3Ry70MdN3MesEs',
    appId: '1:861060933562:web:a62b88134707831d2df83b',
    messagingSenderId: '861060933562',
    projectId: 'smartdoor-fc63e',
    authDomain: 'smartdoor-fc63e.firebaseapp.com',
    databaseURL: 'https://smartdoor-fc63e-default-rtdb.firebaseio.com',
    storageBucket: 'smartdoor-fc63e.firebasestorage.app',
  );
}
